//
//  AppSymbol.swift
//  ClipKeyboard
//
//  자동 생성 가능 - 정적 SF Symbol 이름 단일 출처(Single Source of Truth).
//  메인앱·키보드(ClipKeyboardExtension)·macOS(.tap) 3개 타겟이 공유한다.
//  하드코딩 리터럴 대신 항상 이 상수를 사용할 것.
//

import Foundation

enum AppSymbol {
    static let appFill = "app.fill"
    static let arrowClockwise = "arrow.clockwise"
    static let arrowCounterclockwise = "arrow.counterclockwise"
    static let arrowDownDocFill = "arrow.down.doc.fill"
    static let arrowLeftCircleFill = "arrow.left.circle.fill"
    static let arrowTriangle2CirclepathCircle = "arrow.triangle.2.circlepath.circle"
    static let arrowUpAndDown = "arrow.up.and.down"
    static let arrowUpAndDownAndArrowLeftAndRight = "arrow.up.and.down.and.arrow.left.and.right"
    static let arrowUpArrowDown = "arrow.up.arrow.down"
    static let arrowUpDocFill = "arrow.up.doc.fill"
    static let arrowUpForwardApp = "arrow.up.forward.app"
    static let arrowUpForwardAppFill = "arrow.up.forward.app.fill"
    static let arrowUturnBackward = "arrow.uturn.backward"
    static let birdFill = "bird.fill"
    static let bookClosed = "book.closed"
    static let bookPages = "book.pages"
    static let booksVerticalFill = "books.vertical.fill"
    static let calendar = "calendar"
    static let checkmark = "checkmark"
    static let chevronUpChevronDown = "chevron.up.chevron.down"
    static let checkmarkCircle = "checkmark.circle"
    static let checkmarkCircleFill = "checkmark.circle.fill"
    static let checkmarkSealFill = "checkmark.seal.fill"
    static let checkmarkShieldFill = "checkmark.shield.fill"
    static let chartBarXaxis = "chart.bar.xaxis"
    static let chevronDown = "chevron.down"
    static let chevronForward = "chevron.forward"
    static let chevronRight = "chevron.right"
    static let chevronRightCircleFill = "chevron.right.circle.fill"
    static let chevronUp = "chevron.up"
    /// 단축어 마트 - 차려 둔 것에서 골라 담는 자리.
    static let bagFill = "bag.fill"
    static let circle = "circle"
    static let circleFill = "circle.fill"
    static let clock = "clock"
    static let clockArrowCirclepath = "clock.arrow.circlepath"
    static let clockBadgeCheckmarkFill = "clock.badge.checkmark.fill"
    static let command = "command"
    static let crownFill = "crown.fill"
    static let cupAndSaucerFill = "cup.and.saucer.fill"
    static let curlybraces = "curlybraces"
    static let deleteLeft = "delete.left"
    static let deleteLeftFill = "delete.left.fill"
    static let docFill = "doc.fill"
    static let docOnClipboard = "doc.on.clipboard"
    static let docOnClipboardFill = "doc.on.clipboard.fill"
    static let docOnDoc = "doc.on.doc"
    static let docPlaintext = "doc.plaintext"
    static let docText = "doc.text"
    static let ellipsisCircle = "ellipsis.circle"
    static let envelopeBadge = "envelope.badge"
    /// 문질러 담기 - 잘못 담은 글자를 빼는 지우개.
    static let eraser = "eraser"
    static let eraserFill = "eraser.fill"
    static let exclamationmarkCircleFill = "exclamationmark.circle.fill"
    static let exclamationmarkTriangleFill = "exclamationmark.triangle.fill"
    static let eyeFill = "eye.fill"
    static let eyes = "eyes"
    static let figureRun = "figure.run"
    static let figureWalk = "figure.walk"
    static let figureWalkCircle = "figure.walk.circle"
    static let flagCheckered = "flag.checkered"
    static let forkKnife = "fork.knife"
    static let folder = "folder"
    static let folderBadgeGearshape = "folder.badge.gearshape"
    static let folderBadgePlus = "folder.badge.plus"
    static let gear = "gear"
    static let gearshape = "gearshape"
    static let giftFill = "gift.fill"
    static let globe = "globe"
    static let globeAsiaAustraliaFill = "globe.asia.australia.fill"
    /// 문질러 담기 - 사진을 끌어 옮기는 손.
    static let handDraw = "hand.draw"
    static let handTap = "hand.tap"
    static let heartFill = "heart.fill"
    static let icloudAndArrowDown = "icloud.and.arrow.down"
    static let icloudAndArrowUp = "icloud.and.arrow.up"
    static let icloudFill = "icloud.fill"
    static let infoCircle = "info.circle"
    static let infoCircleFill = "info.circle.fill"
    static let keyFill = "key.fill"
    static let keyboard = "keyboard"
    static let keyboardBadgeEye = "keyboard.badge.eye"
    static let lightbulb = "lightbulb"
    static let lightbulbFill = "lightbulb.fill"
    static let line3HorizontalDecreaseCircle = "line.3.horizontal.decrease.circle"
    static let link = "link"
    static let listBullet = "list.bullet"
    static let listBulletRectangle = "list.bullet.rectangle"
    /// 배운 캐럿 자리 스위치(단축어 편집).
    static let musicNote = "music.note"
    static let playTvFill = "play.tv.fill"
    static let textCursor = "text.cursor"
    static let lockFill = "lock.fill"
    static let lockOpenFill = "lock.open.fill"
    static let lockShield = "lock.shield"
    static let lockShieldFill = "lock.shield.fill"
    static let macbook = "macbook"
    static let magnifyingglass = "magnifyingglass"
    static let menubarRectangle = "menubar.rectangle"   // 맥 메뉴바 앱 안내
    static let minusCircleFill = "minus.circle.fill"
    static let number = "number"
    static let paperplaneFill = "paperplane.fill"
    static let pawprintFill = "pawprint.fill"
    static let pencil = "pencil"
    static let pencilCircleFill = "pencil.circle.fill"
    static let pencilTip = "pencil.tip"
    static let personCropCircleBadgeCheckmark = "person.crop.circle.badge.checkmark"
    static let photo = "photo"
    static let photoFill = "photo.fill"
    static let photoBadgePlus = "photo.badge.plus"
    static let photoOnRectangleAngled = "photo.on.rectangle.angled"
    static let plus = "plus"
    static let plusCircle = "plus.circle"
    static let plusCircleFill = "plus.circle.fill"
    static let questionmarkCircle = "questionmark.circle"
    static let questionmarkCircleFill = "questionmark.circle.fill"
    static let quoteOpening = "quote.opening"
    static let rectangle3Group = "rectangle.3.group"
    static let rectangleCompressVertical = "rectangle.compress.vertical"
    static let rectangleGrid1x2 = "rectangle.grid.1x2"
    static let returnLeft = "return"
    static let `repeat` = "repeat"
    static let space = "space"
    static let sparkles = "sparkles"
    static let squareAndArrowDown = "square.and.arrow.down"
    static let squareAndArrowUp = "square.and.arrow.up"
    static let squareAndPencil = "square.and.pencil"
    static let squareGrid2x2 = "square.grid.2x2"
    static let squareGrid2x2Fill = "square.grid.2x2.fill"
    static let squareStack3dUpFill = "square.stack.3d.up.fill"
    static let star = "star"
    static let starCircleFill = "star.circle.fill"
    static let starFill = "star.fill"
    static let tag = "tag"
    static let tagFill = "tag.fill"
    static let textAlignleft = "text.alignleft"
    /// 문질러 담기 - 줄이 바뀐 자리를 줄바꿈으로 살릴지.
    static let textJustify = "text.justify"
    /// 사진 속 글자를 읽어 값으로 넣는 자리에 쓴다(일괄 가져오기·단축어 내용).
    static let textViewfinder = "text.viewfinder"
    static let cameraViewfinder = "camera.viewfinder"
    static let tramFill = "tram.fill"
    static let trash = "trash"
    static let trashCircleFill = "trash.circle.fill"
    static let trashFill = "trash.fill"
    static let tray = "tray"
    static let trayFull = "tray.full"
    static let wandAndSparkles = "wand.and.sparkles"
    static let xmark = "xmark"
    static let xmarkCircle = "xmark.circle"
    static let xmarkCircleFill = "xmark.circle.fill"
}

